spring:
  datasource:
    platform: h2
    url: "jdbc:h2:file:./static/gefu"
    driverClassName: org.h2.Driver
    username: sa
    password: pass
    initialization-mode: always
    continue-on-error: true
  h2:
    console:
      enabled: true
      settings.trace: false
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect

        
        